/**
 * scripts/generate-training-data.ts
 *
 * Generates 1,500 grounded Q&A pairs for Gemma 3 27B supervised fine-tuning.
 *
 * Each pair is seeded by a random verse, contextualized via the same
 * hybridSearch pipeline used in production, and generated by Claude Sonnet
 * with tool-use so the output is structurally validated before it's kept.
 *
 * Run:  npx tsx scripts/generate-training-data.ts
 *
 * Outputs (data/training/):
 *   verselink-sft.jsonl          — full dataset
 *   verselink-sft-train.jsonl    — 85% split
 *   verselink-sft-val.jsonl      — 10% split
 *   verselink-sft-test.jsonl     — 5% split  (eval set held-out)
 *   rejections.log               — failed attempts with reasons
 *
 * Resume: if verselink-sft.jsonl already has N lines, generation starts at N.
 * To restart clean, delete the file first.
 */

// dotenv MUST load before any lib/ imports — those modules read process.env
// at import time (module-level const) so env vars must already be set.
import { config } from 'dotenv';
config({ path: '.env.local' });

import Anthropic from '@anthropic-ai/sdk';
import { createClient } from '@supabase/supabase-js';
import { GoogleGenerativeAI } from '@google/generative-ai';
import fs from 'fs';
import path from 'path';
import * as rlp from 'readline/promises';
import { stdin as input, stdout as output } from 'process';

// ── CONFIG ────────────────────────────────────────────────────────────────────

const TARGET_PAIRS    = 1500;
const SAMPLE_SIZE     = 10;    // pause here for quality review on first run
const MAX_ATTEMPTS    = 3;     // retries before discarding a seed verse
const DEDUP_THRESHOLD = 0.85;  // cosine similarity vs eval questions → reject
const SEED            = 42;    // fixed RNG seed for reproducible splits

// Rate limits: Gemini free tier allows ~1500 req/min; be conservative
const EMBED_WAIT_MS  = 120;    // between Gemini embedding calls
const GEN_WAIT_MS    = 300;    // between Claude generation calls

// ── PRICING (Claude Sonnet 4.6) ───────────────────────────────────────────────

const INPUT_PRICE_PER_MTOK  = 3.00;
const OUTPUT_PRICE_PER_MTOK = 15.00;
const AVG_INPUT_TOKENS       = 2500;   // empirical from baseline run
const AVG_OUTPUT_TOKENS      = 400;
const COST_CEILING           = 30.00;

// ── SPLITS ────────────────────────────────────────────────────────────────────

const TRAIN_FRAC = 0.85;
const VAL_FRAC   = 0.10;
// remaining 0.05 → test

// ── PATHS ─────────────────────────────────────────────────────────────────────

const DATA_DIR        = path.join(process.cwd(), 'data', 'training');
const FULL_PATH       = path.join(DATA_DIR, 'verselink-sft.jsonl');
const TRAIN_PATH      = path.join(DATA_DIR, 'verselink-sft-train.jsonl');
const VAL_PATH        = path.join(DATA_DIR, 'verselink-sft-val.jsonl');
const TEST_PATH       = path.join(DATA_DIR, 'verselink-sft-test.jsonl');
const REJECTIONS_LOG  = path.join(DATA_DIR, 'rejections.log');

// ── CLIENTS ───────────────────────────────────────────────────────────────────

// All clients are initialized HERE (module body), not inside imported libs.
// tsx hoists all import/require calls before any module body code runs, so
// config() above executes before these lines — env vars are set in time.
const anthropic = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY! });

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!
);

// Gemini embedding client — same config as lib/search.ts
// (apiVersion:'v1' required for gemini-embedding-001)
const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY!);
const geminiModel = genAI.getGenerativeModel(
  { model: 'gemini-embedding-001' },
  { apiVersion: 'v1' }
);

// ── ROW SHAPES (needed by search helpers below) ───────────────────────────────
type VerseRow = { book: string; chapter: number; verse: number; text: string };
type ChunkRow = { book: string; chapter: number; text: string };

// ── SEARCH HELPERS (inlined to avoid lib/supabase.ts eager-init side-effect) ──

async function embedText(text: string): Promise<number[]> {
  const result = await geminiModel.embedContent({
    content: { parts: [{ text }], role: 'user' },
    // @ts-expect-error outputDimensionality is valid but missing from older SDK types
    outputDimensionality: 768,
  });
  return result.embedding.values;
}

async function hybridSearch(query: string, verseK = 3, chunkK = 1) {
  const vec = await embedText(query);
  const [verseRes, chunkRes] = await Promise.all([
    supabase.rpc('match_verses', { query_embedding: vec, match_count: verseK }),
    supabase.rpc('match_chunks', { query_embedding: vec, match_count: chunkK }),
  ]);
  if (verseRes.error) throw new Error(`Verse search: ${verseRes.error.message}`);
  if (chunkRes.error) throw new Error(`Chunk search: ${chunkRes.error.message}`);
  return {
    verses: (verseRes.data ?? []) as VerseRow[],
    chunks: (chunkRes.data ?? []) as ChunkRow[],
  };
}

// ── TYPES ─────────────────────────────────────────────────────────────────────

interface SFTMessage  { role: 'system' | 'user' | 'assistant'; content: string }
interface SFTExample  { messages: SFTMessage[] }
interface GeneratedPair {
  question:  string;
  answer:    string;
  citations: Array<{ ref: string; text: string; relevance: string }>;
}

// ── UTILITIES ─────────────────────────────────────────────────────────────────

const sleep = (ms: number) => new Promise<void>(r => setTimeout(r, ms));

function countExistingLines(filePath: string): number {
  if (!fs.existsSync(filePath)) return 0;
  return fs.readFileSync(filePath, 'utf-8').split('\n').filter(l => l.trim()).length;
}

// Mulberry32 — high-quality seeded PRNG, deterministic across runs
function seededRng(seed: number) {
  let s = seed;
  return (): number => {
    s = (s + 0x6D2B79F5) | 0;
    let t = Math.imul(s ^ (s >>> 15), 1 | s);
    t = t + Math.imul(t ^ (t >>> 7), 61 | t) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

function seededShuffle<T>(arr: T[], seed: number): T[] {
  const rng = seededRng(seed);
  const result = [...arr];
  for (let i = result.length - 1; i > 0; i--) {
    const j = Math.floor(rng() * (i + 1));
    [result[i], result[j]] = [result[j], result[i]];
  }
  return result;
}

// Cosine similarity — Gemini embeddings are unit vectors so this equals dot product,
// but computing the full formula is safer in case of numerical drift.
function cosineSim(a: number[], b: number[]): number {
  let dot = 0, magA = 0, magB = 0;
  for (let i = 0; i < a.length; i++) {
    dot  += a[i] * b[i];
    magA += a[i] * a[i];
    magB += b[i] * b[i];
  }
  const denom = Math.sqrt(magA) * Math.sqrt(magB);
  return denom === 0 ? 0 : dot / denom;
}

function logRejection(reason: string, detail: string) {
  fs.appendFileSync(REJECTIONS_LOG, `[${new Date().toISOString()}] ${reason}: ${detail}\n`);
}

// ── CONTEXT / PROMPT BUILDERS ─────────────────────────────────────────────────

// Exact replica of the system prompt format used in /app/api/ask/route.ts.
// This is what goes into the SFT example's system message so the model
// trains on inputs that look identical to production.
function buildProductionPrompt(verses: VerseRow[], chunks: ChunkRow[]): string {
  const scriptureCtx = verses
    .map((v, i) => `[${i + 1}] ${v.book} ${v.chapter}:${v.verse} — "${v.text}"`)
    .join('\n');

  const commentaryCtx = chunks
    .map((c, i) => `[${verses.length + i + 1}] Matthew Henry on ${c.book} ${c.chapter} — "${c.text}"`)
    .join('\n\n');

  return `You are a Bible study assistant. Answer questions using ONLY the Scripture verses and commentary excerpts provided below. Do not use any Bible knowledge or theological knowledge outside what is given.

Rules:
1. Only cite verses and commentary from the provided lists. Never invent references.
2. If the provided material does not adequately address the question, say so honestly.
3. Every claim must be tied to a specific item from the lists.
4. Be warm, pastoral, and clear — you are helping someone study Scripture.
5. When commentary is available, use it to explain context or application — but Scripture takes priority.

SCRIPTURE VERSES:
${scriptureCtx}${chunks.length > 0 ? `\n\nMATTHEW HENRY COMMENTARY EXCERPTS:\n${commentaryCtx}` : ''}`;
}

// Generation prompt wraps the production prompt with authoring instructions.
// Claude sees the context and writes a question + answer grounded in it.
function buildGenerationPrompt(productionPrompt: string): string {
  return `You are authoring fine-tuning training data for a Bible study AI. Given the context below, generate ONE high-quality Q&A pair.

Requirements:
— The question must be specific to THIS context — answerable from the verses and commentary provided, not from general Bible knowledge
— The answer must be 2–4 sentences, warm and pastoral in tone, using only what is in the context
— Every citation ref must exactly match a label visible in the context (e.g. "John 3:16", "Matthew Henry on John 3")
— Require at least one citation

Vary question style across pairs — use all of these formats:
  "What does Scripture say about [topic]?"     "How should I [action in a situation]?"
  "What does [verse] mean for daily life?"     "Why does God [action or attribute]?"
  "How can I [spiritual practice]?"            "What is the biblical view of [concept]?"
  "Can you explain what [passage] is teaching?"

---
${productionPrompt}`;
}

// ── TOOL SCHEMA ───────────────────────────────────────────────────────────────

const TRAINING_TOOL = {
  name: 'training_pair',
  description: 'Output one grounded Q&A training pair from the provided context.',
  input_schema: {
    type: 'object' as const,
    properties: {
      question: {
        type: 'string' as const,
        description: 'A natural question answerable from the context above — not generic Bible trivia.',
      },
      answer: {
        type: 'string' as const,
        description: '2–4 sentences, pastoral in tone, grounded only in the provided context.',
      },
      citations: {
        type: 'array' as const,
        description: 'Context refs that support the answer. Use the exact labels visible in the context.',
        items: {
          type: 'object' as const,
          properties: {
            ref:       { type: 'string' as const, description: 'e.g. "John 3:16" or "Matthew Henry on John 3"' },
            text:      { type: 'string' as const, description: 'Exact quoted text from the context.' },
            relevance: { type: 'string' as const, description: 'Why this source supports the answer.' },
          },
          required: ['ref', 'text', 'relevance'] as string[],
        },
      },
    },
    required: ['question', 'answer', 'citations'] as string[],
  },
};

// ── CORE GENERATION ───────────────────────────────────────────────────────────

async function generateOne(
  totalVerses: number,
  evalEmbeddings: number[][]
): Promise<SFTExample | null> {
  for (let attempt = 1; attempt <= MAX_ATTEMPTS; attempt++) {
    try {
      // 1. Pick a random seed verse by row offset
      const offset = Math.floor(Math.random() * totalVerses);
      const { data: rows, error: seedErr } = await supabase
        .from('verses')
        .select('id, book, chapter, verse, text')
        .range(offset, offset);
      if (seedErr || !rows?.length) throw new Error(`Seed fetch failed: ${seedErr?.message}`);
      const seed = rows[0];

      // 2. hybridSearch with the seed verse as the query.
      //    Requesting 3 verses: the seed verse will rank #1; the other two are
      //    related verses retrieved by semantic similarity (same as production).
      //    1 commentary chunk adds theological depth.
      const { verses, chunks } = await hybridSearch(seed.text, 3, 1);
      await sleep(EMBED_WAIT_MS); // Gemini rate limit

      // 3. Build valid-ref sets for citation validation
      const verseRefs = verses.map(v => `${v.book} ${v.chapter}:${v.verse}`);
      const chunkRefs = chunks.map(c => `Matthew Henry on ${c.book} ${c.chapter}`);
      const allRefs   = [...verseRefs, ...chunkRefs];

      // 4. Production system prompt — this is exactly what the model sees during inference
      const productionPrompt = buildProductionPrompt(verses, chunks);

      // 5. Call Claude Sonnet to generate the Q&A pair
      const msg = await anthropic.messages.create({
        model:      'claude-sonnet-4-6',
        max_tokens: 800,
        system:     buildGenerationPrompt(productionPrompt),
        messages:   [{ role: 'user', content: 'Generate one Q&A training pair for the context above.' }],
        tools:      [TRAINING_TOOL],
        tool_choice: { type: 'tool' as const, name: 'training_pair' },
      });

      const block = msg.content.find(b => b.type === 'tool_use') as
        | { type: 'tool_use'; input: GeneratedPair }
        | undefined;
      if (!block) throw new Error('No tool_use block in response');
      const gen = block.input;

      // 6. Validate: require at least one citation
      if (!gen.citations?.length) {
        logRejection('no_citations', `q="${gen.question}"`);
        continue;
      }

      // 7. Validate: every cited ref must be traceable to the context.
      //    Using substring containment in either direction (same logic as the eval
      //    isFaithful check) to handle "John 3:16" vs "John 3:16-17" variants.
      const badCitations = gen.citations.filter(
        c => !allRefs.some(r => r.includes(c.ref) || c.ref.includes(r))
      );
      if (badCitations.length > 0) {
        logRejection(
          'citation_mismatch',
          `bad=[${badCitations.map(c => c.ref).join(', ')}] valid=[${allRefs.join(', ')}] attempt=${attempt}`
        );
        continue;
      }

      // 8. Near-duplicate check: embed the question and compare against the 30
      //    held-out eval questions. If similarity ≥ 0.85 to any eval question,
      //    reject — we must keep the eval set truly unseen.
      const qVec = await embedText(gen.question);
      await sleep(EMBED_WAIT_MS);
      const maxSim = evalEmbeddings.reduce((m, e) => Math.max(m, cosineSim(qVec, e)), 0);
      if (maxSim >= DEDUP_THRESHOLD) {
        logRejection('near_duplicate', `sim=${maxSim.toFixed(3)} q="${gen.question}"`);
        continue;
      }

      // 9. All checks passed — build the SFT example
      return {
        messages: [
          { role: 'system',    content: productionPrompt },
          { role: 'user',      content: gen.question },
          { role: 'assistant', content: gen.answer },
        ],
      };
    } catch (err) {
      logRejection(`exception_attempt_${attempt}`, String(err));
      if (attempt < MAX_ATTEMPTS) await sleep(1000); // back off before retry
    }
  }
  return null;
}

// ── SPLITS ────────────────────────────────────────────────────────────────────

function writeSplits(totalGenerated: number) {
  const lines = fs.readFileSync(FULL_PATH, 'utf-8')
    .split('\n')
    .filter(l => l.trim());

  const shuffled = seededShuffle(lines, SEED);
  const nTrain   = Math.floor(shuffled.length * TRAIN_FRAC);
  const nVal     = Math.floor(shuffled.length * VAL_FRAC);
  const nTest    = shuffled.length - nTrain - nVal;

  fs.writeFileSync(TRAIN_PATH, shuffled.slice(0, nTrain).join('\n') + '\n');
  fs.writeFileSync(VAL_PATH,   shuffled.slice(nTrain, nTrain + nVal).join('\n') + '\n');
  fs.writeFileSync(TEST_PATH,  shuffled.slice(nTrain + nVal).join('\n') + '\n');

  console.log(`\nSplits written (seed=${SEED}, total=${shuffled.length}):`);
  console.log(`  Train ${nTrain}  → verselink-sft-train.jsonl`);
  console.log(`  Val   ${nVal}   → verselink-sft-val.jsonl`);
  console.log(`  Test  ${nTest}   → verselink-sft-test.jsonl`);
}

// ── MAIN ──────────────────────────────────────────────────────────────────────

async function main() {
  // ── Cost estimate ─────────────────────────────────────────────────────────
  const estimatedCost =
    TARGET_PAIRS * AVG_INPUT_TOKENS  * INPUT_PRICE_PER_MTOK  / 1_000_000 +
    TARGET_PAIRS * AVG_OUTPUT_TOKENS * OUTPUT_PRICE_PER_MTOK / 1_000_000;

  console.log(`\n${'─'.repeat(60)}`);
  console.log(`VerseLink SFT dataset generator`);
  console.log(`${'─'.repeat(60)}`);
  console.log(`Target pairs : ${TARGET_PAIRS}`);
  console.log(`Model        : claude-sonnet-4-6`);
  console.log(`Est. cost    : $${estimatedCost.toFixed(2)}`);
  console.log(`  (${AVG_INPUT_TOKENS} input + ${AVG_OUTPUT_TOKENS} output tokens/call × $${INPUT_PRICE_PER_MTOK}/$${OUTPUT_PRICE_PER_MTOK} per Mtok)`);
  console.log(`  Gemini embedding calls add ~$0.00 (free tier)`);
  console.log(`Ceiling      : $${COST_CEILING}`);
  console.log(`${'─'.repeat(60)}\n`);

  if (estimatedCost > COST_CEILING) {
    console.error(`Estimated cost $${estimatedCost.toFixed(2)} exceeds ceiling $${COST_CEILING}. Aborting — adjust TARGET_PAIRS or confirm pricing.`);
    process.exit(1);
  }

  // ── Embed eval questions for near-duplicate detection ─────────────────────
  console.log('Embedding 30 eval questions for dedup detection...');
  const evalRaw: Array<{ question: string }> = JSON.parse(
    fs.readFileSync(path.join(process.cwd(), 'evals', 'questions.json'), 'utf-8')
  );
  const evalEmbeddings: number[][] = [];
  for (const q of evalRaw) {
    evalEmbeddings.push(await embedText(q.question));
    await sleep(EMBED_WAIT_MS);
  }
  console.log(`✓ ${evalEmbeddings.length} eval embeddings cached\n`);

  // ── Get verse count ───────────────────────────────────────────────────────
  const { count: totalVerses, error: countErr } = await supabase
    .from('verses')
    .select('*', { count: 'exact', head: true });
  if (countErr || !totalVerses) throw new Error(`Verse count failed: ${countErr?.message}`);
  console.log(`Verse pool: ${totalVerses.toLocaleString()} rows`);

  // ── Resume detection ──────────────────────────────────────────────────────
  fs.mkdirSync(DATA_DIR, { recursive: true });
  const existingCount = countExistingLines(FULL_PATH);
  const isResume = existingCount > 0;
  if (isResume) {
    console.log(`Resuming: ${existingCount} pairs already in ${FULL_PATH}`);
  } else {
    fs.writeFileSync(FULL_PATH, ''); // truncate for fresh run
  }
  console.log(`Generating ${TARGET_PAIRS - existingCount} more pairs...\n`);

  // ── Generation loop ───────────────────────────────────────────────────────
  let generated   = existingCount;
  let rejected    = 0;
  const sampleBuf: SFTExample[] = [];

  for (let i = generated; i < TARGET_PAIRS; i++) {
    const pair = await generateOne(totalVerses, evalEmbeddings);

    if (pair) {
      fs.appendFileSync(FULL_PATH, JSON.stringify(pair) + '\n');
      generated++;
      if (!isResume && generated <= SAMPLE_SIZE) sampleBuf.push(pair);
    } else {
      rejected++;
    }

    // Progress tick every 50 generated pairs
    if (generated > 0 && generated % 50 === 0 && generated < TARGET_PAIRS) {
      console.log(`  [${generated}/${TARGET_PAIRS}]  ${rejected} rejected so far`);
    }

    // ── 10-pair quality gate (first run only) ─────────────────────────────
    if (!isResume && generated === SAMPLE_SIZE) {
      console.log('\n' + '═'.repeat(72));
      console.log('SAMPLE REVIEW — first 10 generated pairs');
      console.log('═'.repeat(72));

      sampleBuf.forEach((s, idx) => {
        const ctxRefs = s.messages[0].content
          .split('\n')
          .filter(l => /^\[\d+\]/.test(l.trim()))
          .map(l => l.trim().slice(0, 72));

        console.log(`\n── Pair ${idx + 1} ${'─'.repeat(56)}`);
        console.log(`Q: ${s.messages[1].content}`);
        console.log(`A: ${s.messages[2].content}`);
        console.log(`   Context refs:`);
        ctxRefs.forEach(r => console.log(`     ${r}`));
      });

      console.log('\n' + '═'.repeat(72));
      console.log(`\n${rejected} rejected so far (check ${REJECTIONS_LOG} for details)`);

      const rl  = rlp.createInterface({ input, output });
      const ans = await rl.question(
        '\nReview the 10 pairs above. Continue generating remaining 1,490? [y/N]: '
      );
      rl.close();

      if (ans.trim().toLowerCase() !== 'y') {
        console.log(`\nStopped at sample. ${FULL_PATH} has ${generated} pairs.`);
        process.exit(0);
      }
      console.log('\nContinuing...\n');
    }

    await sleep(GEN_WAIT_MS);
  }

  // ── Write splits ──────────────────────────────────────────────────────────
  writeSplits(generated);

  console.log(`\n${'─'.repeat(60)}`);
  console.log(`Done.`);
  console.log(`  Generated : ${generated} pairs`);
  console.log(`  Rejected  : ${rejected}`);
  console.log(`  Full file : ${FULL_PATH}`);
  console.log(`  Rejections: ${REJECTIONS_LOG}`);
  console.log(`${'─'.repeat(60)}\n`);
}

main().catch(err => {
  console.error(err);
  process.exit(1);
});
